env:
  browser: true
  es6: true
  node: true
root: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
plugins:
  - prettier
  - '@typescript-eslint'
  - react
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
parser: '@typescript-eslint/parser'
settings:
  react:
    version: 'detect'
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  prettier/prettier: warn
  no-console:
    - error
    - allow:
        - warn
        - error
